export const PERMISSIONS = {
  CATEGORY: {
    CREATE: "CATEGORY_CREATE",
    READ_ALL: "CATEGORY_READ_ALL",
    READ_ONE: "CATEGORY_READ_ONE",
    UPDATE: "CATEGORY_UPDATE",
    DELETE: "CATEGORY_DELETE",
  },
  COLLECTION: {
    CREATE: "COLLECTION_CREATE",
    READ_ALL: "COLLECTION_READ_ALL",
    READ_ONE: "COLLECTION_READ_ONE",
    UPDATE: "COLLECTION_UPDATE",
    DELETE: "COLLECTION_DELETE",
  },
  COLOR: {
    CREATE: "COLOR_CREATE",
    READ_ALL: "COLOR_READ_ALL",
    READ_ONE: "COLOR_READ_ONE",
    UPDATE: "COLOR_UPDATE",
    DELETE: "COLOR_DELETE",
  },
  DISCOUNT: {
    CREATE: "DISCOUNT_CREATE",
    READ_ALL: "DISCOUNT_READ_ALL",
    READ_ONE: "DISCOUNT_READ_ONE",
    UPDATE: "DISCOUNT_UPDATE",
    DELETE: "DISCOUNT_DELETE",
  },
  WHOLESALE: {
    CREATE: "WHOLESALE_CREATE",
    READ_ALL: "WHOLESALE_READ_ALL",
    READ_ONE: "WHOLESALE_READ_ONE",
    UPDATE: "WHOLESALE_UPDATE",
    DELETE: "WHOLESALE_DELETE",
  },
  PRODUCT: {
    CREATE: "PRODUCT_CREATE",
    READ_ALL: "PRODUCT_READ_ALL",
    READ_ONE: "PRODUCT_READ_ONE",
    UPDATE: "PRODUCT_UPDATE",
    DELETE: "PRODUCT_DELETE",
  },
  SIZE: {
    CREATE: "SIZE_CREATE",
    READ_ALL: "SIZE_READ_ALL",
    READ_ONE: "SIZE_READ_ONE",
    UPDATE: "SIZE_UPDATE",
    DELETE: "SIZE_DELETE",
  },
  DEPOT: {
    CREATE: "DEPOT_CREATE",
    READ_ALL: "DEPOT_READ_ALL",
    READ_ONE: "DEPOT_READ_ONE",
    UPDATE: "DEPOT_UPDATE",
    DELETE: "DEPOT_DELETE",
  },
  STOCK: {
    CREATE: "STOCK_CREATE",
    READ_ALL: "STOCK_READ_ALL",
    READ_ONE: "STOCK_READ_ONE",
    UPDATE: "STOCK_UPDATE",
    DELETE: "STOCK_DELETE",
    STOCK_COUNT_PIECE: "STOCK_COUNT_PIECE",
  },
  PERMISSION: {
    READ_ALL: "PERMISSION_READ_ALL",
    READ_ONE: "PERMISSION_READ_ONE",
  },
  ROLE: {
    CREATE: "ROLE_CREATE",
    READ_ALL: "ROLE_READ_ALL",
    READ_ONE: "ROLE_READ_ONE",
    UPDATE: "ROLE_UPDATE",
    DELETE: "ROLE_DELETE",
    ASSIGN_PERMISSION: "ROLE_PERMISSION_ASSIGN",
  },
  USER: {
    CREATE: "USER_CREATE",
    READ_ALL: "USER_READ_ALL",
    READ_ONE: "USER_READ_ONE",
    UPDATE: "USER_UPDATE",
    DELETE: "USER_DELETE",
    UPDATE_PASSWORD: "USER_UPDATE_PASSWORD",
  },
  MOVEMENT: {
    READ_ALL: "MOVEMENT_READ_ALL",
    CREATE: "MOVEMENT_CREATE",
    MOVEMENT_INBOUND: "MOVEMENT_INBOUND",
    MOVEMENT_SALE: "MOVEMENT_SALE",
    MOVEMENT_TRANSFERT: "MOVEMENT_TRANSFERT",
    MOVEMENT_RETURN: "MOVEMENT_RETURN",
    MOVEMENT_CANCEL: "MOVEMENT_CANCEL",
  },
  DASHBOARD: {
    DASHBOARD_STOCK_STAT: "DASHBOARD_STOCK_STAT",
    DASHBOARD_MOVEMENT_STAT: "DASHBOARD_MOVEMENT_STAT",
  },
  ALL: "ALL",
};

export type keyword =
  | "CATEGORY"
  | "COLLECTION"
  | "COLOR"
  | "DISCOUNT"
  | "PRODUCT"
  | "SIZE"
  | "DEPOT"
  | "STOCK"
  | "ROLE"
  | "USER"
  | "MOVEMENT"
  | "DASHBOARD";

export const KEYWORD_LABELS: Record<keyword, string> = {
  CATEGORY: "Catégorie",
  COLLECTION: "Collection",
  COLOR: "Couleur",
  DISCOUNT: "Réduction",
  PRODUCT: "Produit",
  SIZE: "Taille",
  DEPOT: "Dépôt",
  STOCK: "Stock",
  ROLE: "Rôle",
  USER: "Utilisateur",
  MOVEMENT: "Mouvement",
  DASHBOARD: "Tableau de bord",
};

export type action = "CREATE" | "READ_ALL" | "READ_ONE" | "UPDATE" | "DELETE";

export const ACTION_LABELS: Record<action, string> = {
  CREATE: "Ajouter",
  READ_ALL: "Voir tout",
  READ_ONE: "Voir",
  UPDATE: "Modifier",
  DELETE: "Supprimer",
};

export const ACTIONS: action[] = [
  "CREATE",
  "READ_ALL",
  "READ_ONE",
  "UPDATE",
  "DELETE",
];
export const KEYWORDS: keyword[] = [
  "CATEGORY",
  "COLLECTION",
  "COLOR",
  "DISCOUNT",
  "PRODUCT",
  "SIZE",
  "DEPOT",
  "STOCK",
  "ROLE",
  "USER",
  "MOVEMENT",
  "DASHBOARD",
];
